import Wrapper from '@/components/shared/Wrapper/Wrapper'
import './globals.css'
// import Wrapper from './shared/Wrapper'
// import NavBar from './views/NavBar/NavBar'
import { Maven_Pro } from 'next/font/google'
import NavBar from '@/components/views/NavBar'

const inter = Maven_Pro({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"]
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
        <NavBar />
        {children}
        </Wrapper>
        </body>
    </html>
  )
}
